
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
CatchSelfTest is a Catch v1.0 b10 host application.
Run with -? for options

-------------------------------------------------------------------------------
./failing/TestClass/failingCase
-------------------------------------------------------------------------------
Users/philnash/Dev/OSS/Catch/projects/SelfTest/ClassTests.cpp
...............................................................................

Users/philnash/Dev/OSS/Catch/projects/SelfTest/ClassTests.cpp: FAILED:
  REQUIRE( s == "world" )
with expansion:
  "hello" == "world"

-------------------------------------------------------------------------------
./failing/Fixture/failingCase
-------------------------------------------------------------------------------
Users/philnash/Dev/OSS/Catch/projects/SelfTest/ClassTests.cpp
...............................................................................

Users/philnash/Dev/OSS/Catch/projects/SelfTest/ClassTests.cpp: FAILED:
  REQUIRE( m_a == 2 )
with expansion:
  1 == 2

-------------------------------------------------------------------------------
./failing/conditions/equality
-------------------------------------------------------------------------------
Users/philnash/Dev/OSS/Catch/projects/SelfTest/ConditionTests.cpp
...............................................................................

Users/philnash/Dev/OSS/Catch/projects/SelfTest/ConditionTests.cpp: FAILED:
  CHECK( data.int_seven == 6 )
with expansion:
  7 == 6

Users/philnash/Dev/OSS/Catch/projects/SelfTest/ConditionTests.cpp: FAILED:
  CHECK( data.int_seven == 8 )
with expansion:
  7 == 8

Users/philnash/Dev/OSS/Catch/projects/SelfTest/ConditionTests.cpp: FAILED:
  CHECK( data.int_seven == 0 )
with expansion:
  7 == 0

Users/philnash/Dev/OSS/Catch/projects/SelfTest/ConditionTests.cpp: FAILED:
  CHECK( data.float_nine_point_one == Approx( 9.11f ) )
with expansion:
  9.1 == Approx( 9.11 )

Users/philnash/Dev/OSS/Catch/projects/SelfTest/ConditionTests.cpp: FAILED:
  CHECK( data.float_nine_point_one == Approx( 9.0f ) )
with expansion:
  9.1 == Approx( 9 )

Users/philnash/Dev/OSS/Catch/projects/SelfTest/ConditionTests.cpp: FAILED:
  CHECK( data.float_nine_point_one == Approx( 1 ) )
with expansion:
  9.1 == Approx( 1 )

Users/philnash/Dev/OSS/Catch/projects/SelfTest/ConditionTests.cpp: FAILED:
  CHECK( data.float_nine_point_one == Approx( 0 ) )
with expansion:
  9.1 == Approx( 0 )

Users/philnash/Dev/OSS/Catch/projects/SelfTest/ConditionTests.cpp: FAILED:
  CHECK( data.double_pi == Approx( 3.1415 ) )
with expansion:
  3.1415926535 == Approx( 3.1415 )

Users/philnash/Dev/OSS/Catch/projects/SelfTest/ConditionTests.cpp: FAILED:
  CHECK( data.str_hello == "goodbye" )
with expansion:
  "hello" == "goodbye"

Users/philnash/Dev/OSS/Catch/projects/SelfTest/ConditionTests.cpp: FAILED:
  CHECK( data.str_hello == "hell" )
with expansion:
  "hello" == "hell"

Users/philnash/Dev/OSS/Catch/projects/SelfTest/ConditionTests.cpp: FAILED:
  CHECK( data.str_hello == "hello1" )
with expansion:
  "hello" == "hello1"

Users/philnash/Dev/OSS/Catch/projects/SelfTest/ConditionTests.cpp: FAILED:
  CHECK( data.str_hello.size() == 6 )
with expansion:
  5 == 6

Users/philnash/Dev/OSS/Catch/projects/SelfTest/ConditionTests.cpp: FAILED:
  CHECK( x == Approx( 1.301 ) )
with expansion:
  1.3 == Approx( 1.301 )

-------------------------------------------------------------------------------
./failing/conditions/inequality
-------------------------------------------------------------------------------
Users/philnash/Dev/OSS/Catch/projects/SelfTest/ConditionTests.cpp
...............................................................................

Users/philnash/Dev/OSS/Catch/projects/SelfTest/ConditionTests.cpp: FAILED:
  CHECK( data.int_seven != 7 )
with expansion:
  7 != 7

Users/philnash/Dev/OSS/Catch/projects/SelfTest/ConditionTests.cpp: FAILED:
  CHECK( data.float_nine_point_one != Approx( 9.1f ) )
with expansion:
  9.1 != Approx( 9.1 )

Users/philnash/Dev/OSS/Catch/projects/SelfTest/ConditionTests.cpp: FAILED:
  CHECK( data.double_pi != Approx( 3.1415926535 ) )
with expansion:
  3.1415926535 != Approx( 3.14159 )

Users/philnash/Dev/OSS/Catch/projects/SelfTest/ConditionTests.cpp: FAILED:
  CHECK( data.str_hello != "hello" )
with expansion:
  "hello" != "hello"

Users/philnash/Dev/OSS/Catch/projects/SelfTest/ConditionTests.cpp: FAILED:
  CHECK( data.str_hello.size() != 5 )
with expansion:
  5 != 5

-------------------------------------------------------------------------------
./failing/conditions/ordered
-------------------------------------------------------------------------------
Users/philnash/Dev/OSS/Catch/projects/SelfTest/ConditionTests.cpp
...............................................................................

Users/philnash/Dev/OSS/Catch/projects/SelfTest/ConditionTests.cpp: FAILED:
  CHECK( data.int_seven > 7 )
with expansion:
  7 > 7

Users/philnash/Dev/OSS/Catch/projects/SelfTest/ConditionTests.cpp: FAILED:
  CHECK( data.int_seven < 7 )
with expansion:
  7 < 7

Users/philnash/Dev/OSS/Catch/projects/SelfTest/ConditionTests.cpp: FAILED:
  CHECK( data.int_seven > 8 )
with expansion:
  7 > 8

Users/philnash/Dev/OSS/Catch/projects/SelfTest/ConditionTests.cpp: FAILED:
  CHECK( data.int_seven < 6 )
with expansion:
  7 < 6

Users/philnash/Dev/OSS/Catch/projects/SelfTest/ConditionTests.cpp: FAILED:
  CHECK( data.int_seven < 0 )
with expansion:
  7 < 0

Users/philnash/Dev/OSS/Catch/projects/SelfTest/ConditionTests.cpp: FAILED:
  CHECK( data.int_seven < -1 )
with expansion:
  7 < -1

Users/philnash/Dev/OSS/Catch/projects/SelfTest/ConditionTests.cpp: FAILED:
  CHECK( data.int_seven >= 8 )
with expansion:
  7 >= 8

Users/philnash/Dev/OSS/Catch/projects/SelfTest/ConditionTests.cpp: FAILED:
  CHECK( data.int_seven <= 6 )
with expansion:
  7 <= 6

Users/philnash/Dev/OSS/Catch/projects/SelfTest/ConditionTests.cpp: FAILED:
  CHECK( data.float_nine_point_one < 9 )
with expansion:
  9.1 < 9

Users/philnash/Dev/OSS/Catch/projects/SelfTest/ConditionTests.cpp: FAILED:
  CHECK( data.float_nine_point_one > 10 )
with expansion:
  9.1 > 10

Users/philnash/Dev/OSS/Catch/projects/SelfTest/ConditionTests.cpp: FAILED:
  CHECK( data.float_nine_point_one > 9.2 )
with expansion:
  9.1 > 9.2

Users/philnash/Dev/OSS/Catch/projects/SelfTest/ConditionTests.cpp: FAILED:
  CHECK( data.str_hello > "hello" )
with expansion:
  "hello" > "hello"

Users/philnash/Dev/OSS/Catch/projects/SelfTest/ConditionTests.cpp: FAILED:
  CHECK( data.str_hello < "hello" )
with expansion:
  "hello" < "hello"

Users/philnash/Dev/OSS/Catch/projects/SelfTest/ConditionTests.cpp: FAILED:
  CHECK( data.str_hello > "hellp" )
with expansion:
  "hello" > "hellp"

Users/philnash/Dev/OSS/Catch/projects/SelfTest/ConditionTests.cpp: FAILED:
  CHECK( data.str_hello > "z" )
with expansion:
  "hello" > "z"

Users/philnash/Dev/OSS/Catch/projects/SelfTest/ConditionTests.cpp: FAILED:
  CHECK( data.str_hello < "hellm" )
with expansion:
  "hello" < "hellm"

Users/philnash/Dev/OSS/Catch/projects/SelfTest/ConditionTests.cpp: FAILED:
  CHECK( data.str_hello < "a" )
with expansion:
  "hello" < "a"

Users/philnash/Dev/OSS/Catch/projects/SelfTest/ConditionTests.cpp: FAILED:
  CHECK( data.str_hello >= "z" )
with expansion:
  "hello" >= "z"

Users/philnash/Dev/OSS/Catch/projects/SelfTest/ConditionTests.cpp: FAILED:
  CHECK( data.str_hello <= "a" )
with expansion:
  "hello" <= "a"

-------------------------------------------------------------------------------
./failing/conditions/not
-------------------------------------------------------------------------------
Users/philnash/Dev/OSS/Catch/projects/SelfTest/ConditionTests.cpp
...............................................................................

Users/philnash/Dev/OSS/Catch/projects/SelfTest/ConditionTests.cpp: FAILED:
  CHECK( false != false )

Users/philnash/Dev/OSS/Catch/projects/SelfTest/ConditionTests.cpp: FAILED:
  CHECK( true != true )

Users/philnash/Dev/OSS/Catch/projects/SelfTest/ConditionTests.cpp: FAILED:
  CHECK( !true )
with expansion:
  false

Users/philnash/Dev/OSS/Catch/projects/SelfTest/ConditionTests.cpp: FAILED:
  CHECK_FALSE( true )

Users/philnash/Dev/OSS/Catch/projects/SelfTest/ConditionTests.cpp: FAILED:
  CHECK( !trueValue )
with expansion:
  false

Users/philnash/Dev/OSS/Catch/projects/SelfTest/ConditionTests.cpp: FAILED:
  CHECK_FALSE( trueValue )
with expansion:
  !true

Users/philnash/Dev/OSS/Catch/projects/SelfTest/ConditionTests.cpp: FAILED:
  CHECK( !(1 == 1) )
with expansion:
  false

Users/philnash/Dev/OSS/Catch/projects/SelfTest/ConditionTests.cpp: FAILED:
  CHECK_FALSE( 1 == 1 )
with expansion:
  !(1 == 1)

-------------------------------------------------------------------------------
./failing/exceptions/explicit
-------------------------------------------------------------------------------
Users/philnash/Dev/OSS/Catch/projects/SelfTest/ExceptionTests.cpp
...............................................................................

Users/philnash/Dev/OSS/Catch/projects/SelfTest/ExceptionTests.cpp: FAILED:
  CHECK_THROWS_AS( thisThrows() )
due to unexpected exception with message:
  expected exception

Users/philnash/Dev/OSS/Catch/projects/SelfTest/ExceptionTests.cpp: FAILED:
  CHECK_THROWS_AS( thisDoesntThrow() )
because no exception was thrown where one was expected:

Users/philnash/Dev/OSS/Catch/projects/SelfTest/ExceptionTests.cpp: FAILED:
  CHECK_NOTHROW( thisThrows() )
due to unexpected exception with message:
  expected exception

-------------------------------------------------------------------------------
./failing/exceptions/implicit
-------------------------------------------------------------------------------
Users/philnash/Dev/OSS/Catch/projects/SelfTest/ExceptionTests.cpp
...............................................................................

Users/philnash/Dev/OSS/Catch/projects/SelfTest/ExceptionTests.cpp: FAILED:
due to unexpected exception with message:
  unexpected exception

-------------------------------------------------------------------------------
./failing/exceptions/implicit/2
-------------------------------------------------------------------------------
Users/philnash/Dev/OSS/Catch/projects/SelfTest/ExceptionTests.cpp
...............................................................................

Users/philnash/Dev/OSS/Catch/projects/SelfTest/ExceptionTests.cpp: FAILED:
  {Unknown expression after the reported line}
due to unexpected exception with message:
  unexpected exception

-------------------------------------------------------------------------------
./failing/exceptions/implicit/3
  section name
-------------------------------------------------------------------------------
Users/philnash/Dev/OSS/Catch/projects/SelfTest/ExceptionTests.cpp
...............................................................................

Users/philnash/Dev/OSS/Catch/projects/SelfTest/ExceptionTests.cpp: FAILED:
due to unexpected exception with message:
  unexpected exception

-------------------------------------------------------------------------------
./failing/exceptions/implicit/4
-------------------------------------------------------------------------------
Users/philnash/Dev/OSS/Catch/projects/SelfTest/ExceptionTests.cpp
...............................................................................

Users/philnash/Dev/OSS/Catch/projects/SelfTest/ExceptionTests.cpp: FAILED:
  CHECK( thisThrows() == 0 )
due to unexpected exception with message:
  expected exception

-------------------------------------------------------------------------------
./failing/exceptions/custom
-------------------------------------------------------------------------------
Users/philnash/Dev/OSS/Catch/projects/SelfTest/ExceptionTests.cpp
...............................................................................

Users/philnash/Dev/OSS/Catch/projects/SelfTest/ExceptionTests.cpp: FAILED:
due to unexpected exception with message:
  custom exception

-------------------------------------------------------------------------------
./failing/exceptions/custom/nothrow
-------------------------------------------------------------------------------
Users/philnash/Dev/OSS/Catch/projects/SelfTest/ExceptionTests.cpp
...............................................................................

Users/philnash/Dev/OSS/Catch/projects/SelfTest/ExceptionTests.cpp: FAILED:
  REQUIRE_NOTHROW( throwCustom() )
due to unexpected exception with message:
  custom exception - not std

-------------------------------------------------------------------------------
./failing/exceptions/custom/throw
-------------------------------------------------------------------------------
Users/philnash/Dev/OSS/Catch/projects/SelfTest/ExceptionTests.cpp
...............................................................................

Users/philnash/Dev/OSS/Catch/projects/SelfTest/ExceptionTests.cpp: FAILED:
  REQUIRE_THROWS_AS( throwCustom() )
due to unexpected exception with message:
  custom exception - not std

-------------------------------------------------------------------------------
./failing/exceptions/custom/double
-------------------------------------------------------------------------------
Users/philnash/Dev/OSS/Catch/projects/SelfTest/ExceptionTests.cpp
...............................................................................

Users/philnash/Dev/OSS/Catch/projects/SelfTest/ExceptionTests.cpp: FAILED:
due to unexpected exception with message:
  3.14

-------------------------------------------------------------------------------
./failing/message/info/1
-------------------------------------------------------------------------------
Users/philnash/Dev/OSS/Catch/projects/SelfTest/MessageTests.cpp
...............................................................................

Users/philnash/Dev/OSS/Catch/projects/SelfTest/MessageTests.cpp: FAILED:
  REQUIRE( a == 1 )
with expansion:
  2 == 1
with messages:
  this message should be logged
  so should this

-------------------------------------------------------------------------------
./mixed/message/info/2
-------------------------------------------------------------------------------
Users/philnash/Dev/OSS/Catch/projects/SelfTest/MessageTests.cpp
...............................................................................

Users/philnash/Dev/OSS/Catch/projects/SelfTest/MessageTests.cpp: FAILED:
  CHECK( a == 1 )
with expansion:
  2 == 1
with messages:
  this message may be logged later
  this message should be logged

Users/philnash/Dev/OSS/Catch/projects/SelfTest/MessageTests.cpp: FAILED:
  CHECK( a == 0 )
with expansion:
  2 == 0
with message:
  and this, but later

-------------------------------------------------------------------------------
./failing/message/fail
-------------------------------------------------------------------------------
Users/philnash/Dev/OSS/Catch/projects/SelfTest/MessageTests.cpp
...............................................................................

Users/philnash/Dev/OSS/Catch/projects/SelfTest/MessageTests.cpp: FAILED:
explicitly with message:
  This is a failure

-------------------------------------------------------------------------------
./failing/message/sections
  one
-------------------------------------------------------------------------------
Users/philnash/Dev/OSS/Catch/projects/SelfTest/MessageTests.cpp
...............................................................................

Users/philnash/Dev/OSS/Catch/projects/SelfTest/MessageTests.cpp: FAILED:
explicitly with message:
  Message from section one

-------------------------------------------------------------------------------
./failing/message/sections
  two
-------------------------------------------------------------------------------
Users/philnash/Dev/OSS/Catch/projects/SelfTest/MessageTests.cpp
...............................................................................

Users/philnash/Dev/OSS/Catch/projects/SelfTest/MessageTests.cpp: FAILED:
explicitly with message:
  Message from section two

Message from section one
Message from section two
-------------------------------------------------------------------------------
./mixed/message/scoped
-------------------------------------------------------------------------------
Users/philnash/Dev/OSS/Catch/projects/SelfTest/MessageTests.cpp
...............................................................................

Users/philnash/Dev/OSS/Catch/projects/SelfTest/MessageTests.cpp: FAILED:
  REQUIRE( i < 10 )
with expansion:
  10 < 10
with messages:
  current counter 10
  i := 10

-------------------------------------------------------------------------------
just failure
-------------------------------------------------------------------------------
Users/philnash/Dev/OSS/Catch/projects/SelfTest/MessageTests.cpp
...............................................................................

Users/philnash/Dev/OSS/Catch/projects/SelfTest/MessageTests.cpp: FAILED:
explicitly with message:
  Previous info should not be seen

-------------------------------------------------------------------------------
./mixed/Misc/Sections/nested2
  s1
  s2
-------------------------------------------------------------------------------
Users/philnash/Dev/OSS/Catch/projects/SelfTest/MiscTests.cpp
...............................................................................

Users/philnash/Dev/OSS/Catch/projects/SelfTest/MiscTests.cpp: FAILED:
  REQUIRE( a == b )
with expansion:
  1 == 2

-------------------------------------------------------------------------------
./mixed/Misc/Sections/loops
  s1
-------------------------------------------------------------------------------
Users/philnash/Dev/OSS/Catch/projects/SelfTest/MiscTests.cpp
...............................................................................

Users/philnash/Dev/OSS/Catch/projects/SelfTest/MiscTests.cpp: FAILED:
  CHECK( b > a )
with expansion:
  0 > 1

-------------------------------------------------------------------------------
./mixed/Misc/loops
-------------------------------------------------------------------------------
Users/philnash/Dev/OSS/Catch/projects/SelfTest/MiscTests.cpp
...............................................................................

Users/philnash/Dev/OSS/Catch/projects/SelfTest/MiscTests.cpp: FAILED:
  CHECK( ( fib[i] % 2 ) == 0 )
with expansion:
  1 == 0
with message:
  Testing if fib[0] (1) is even

Users/philnash/Dev/OSS/Catch/projects/SelfTest/MiscTests.cpp: FAILED:
  CHECK( ( fib[i] % 2 ) == 0 )
with expansion:
  1 == 0
with message:
  Testing if fib[1] (1) is even

Users/philnash/Dev/OSS/Catch/projects/SelfTest/MiscTests.cpp: FAILED:
  CHECK( ( fib[i] % 2 ) == 0 )
with expansion:
  1 == 0
with message:
  Testing if fib[3] (3) is even

Users/philnash/Dev/OSS/Catch/projects/SelfTest/MiscTests.cpp: FAILED:
  CHECK( ( fib[i] % 2 ) == 0 )
with expansion:
  1 == 0
with message:
  Testing if fib[4] (5) is even

Users/philnash/Dev/OSS/Catch/projects/SelfTest/MiscTests.cpp: FAILED:
  CHECK( ( fib[i] % 2 ) == 0 )
with expansion:
  1 == 0
with message:
  Testing if fib[6] (13) is even

Users/philnash/Dev/OSS/Catch/projects/SelfTest/MiscTests.cpp: FAILED:
  CHECK( ( fib[i] % 2 ) == 0 )
with expansion:
  1 == 0
with message:
  Testing if fib[7] (21) is even

Some information
An error
-------------------------------------------------------------------------------
./failing/info
-------------------------------------------------------------------------------
Users/philnash/Dev/OSS/Catch/projects/SelfTest/MiscTests.cpp
...............................................................................

Users/philnash/Dev/OSS/Catch/projects/SelfTest/MiscTests.cpp: FAILED:
  REQUIRE( false )
with messages:
  hi
  i := 7

-------------------------------------------------------------------------------
./failing/checkedif
-------------------------------------------------------------------------------
Users/philnash/Dev/OSS/Catch/projects/SelfTest/MiscTests.cpp
...............................................................................

Users/philnash/Dev/OSS/Catch/projects/SelfTest/MiscTests.cpp: FAILED:
  CHECKED_IF( flag )
with expansion:
  false

Users/philnash/Dev/OSS/Catch/projects/SelfTest/MiscTests.cpp: FAILED:
  REQUIRE( testCheckedIf( false ) )
with expansion:
  false

-------------------------------------------------------------------------------
./failing/checkedelse
-------------------------------------------------------------------------------
Users/philnash/Dev/OSS/Catch/projects/SelfTest/MiscTests.cpp
...............................................................................

Users/philnash/Dev/OSS/Catch/projects/SelfTest/MiscTests.cpp: FAILED:
  CHECKED_ELSE( flag )
with expansion:
  false

Users/philnash/Dev/OSS/Catch/projects/SelfTest/MiscTests.cpp: FAILED:
  REQUIRE( testCheckedElse( false ) )
with expansion:
  false

-------------------------------------------------------------------------------
./manual/onechar
-------------------------------------------------------------------------------
Users/philnash/Dev/OSS/Catch/projects/SelfTest/MiscTests.cpp
...............................................................................

Users/philnash/Dev/OSS/Catch/projects/SelfTest/MiscTests.cpp: FAILED:
  REQUIRE( false )
with message:
  3

-------------------------------------------------------------------------------
./failing/matchers/Contains
-------------------------------------------------------------------------------
Users/philnash/Dev/OSS/Catch/projects/SelfTest/MiscTests.cpp
...............................................................................

Users/philnash/Dev/OSS/Catch/projects/SelfTest/MiscTests.cpp: FAILED:
  CHECK_THAT( testStringForMatching() Contains( "not there" ) )
with expansion:
  "this string contains 'abc' as a substring" contains: "not there"

-------------------------------------------------------------------------------
./failing/matchers/StartsWith
-------------------------------------------------------------------------------
Users/philnash/Dev/OSS/Catch/projects/SelfTest/MiscTests.cpp
...............................................................................

Users/philnash/Dev/OSS/Catch/projects/SelfTest/MiscTests.cpp: FAILED:
  CHECK_THAT( testStringForMatching() StartsWith( "string" ) )
with expansion:
  "this string contains 'abc' as a substring" starts with: "string"

-------------------------------------------------------------------------------
./failing/matchers/EndsWith
-------------------------------------------------------------------------------
Users/philnash/Dev/OSS/Catch/projects/SelfTest/MiscTests.cpp
...............................................................................

Users/philnash/Dev/OSS/Catch/projects/SelfTest/MiscTests.cpp: FAILED:
  CHECK_THAT( testStringForMatching() EndsWith( "this" ) )
with expansion:
  "this string contains 'abc' as a substring" ends with: "this"

-------------------------------------------------------------------------------
./failing/matchers/Equals
-------------------------------------------------------------------------------
Users/philnash/Dev/OSS/Catch/projects/SelfTest/MiscTests.cpp
...............................................................................

Users/philnash/Dev/OSS/Catch/projects/SelfTest/MiscTests.cpp: FAILED:
  CHECK_THAT( testStringForMatching() Equals( "something else" ) )
with expansion:
  "this string contains 'abc' as a substring" equals: "something else"

-------------------------------------------------------------------------------
./failing/CatchSectionInfiniteLoop
-------------------------------------------------------------------------------
Users/philnash/Dev/OSS/Catch/projects/SelfTest/MiscTests.cpp
...............................................................................

Users/philnash/Dev/OSS/Catch/projects/SelfTest/MiscTests.cpp: FAILED:
explicitly with message:
  to infinity and beyond

-------------------------------------------------------------------------------
./failing/CatchSectionInfiniteLoop
-------------------------------------------------------------------------------
Users/philnash/Dev/OSS/Catch/projects/SelfTest/MiscTests.cpp
...............................................................................

Users/philnash/Dev/OSS/Catch/projects/SelfTest/MiscTests.cpp: FAILED:
explicitly with message:
  to infinity and beyond

-------------------------------------------------------------------------------
./failing/CatchSectionInfiniteLoop
-------------------------------------------------------------------------------
Users/philnash/Dev/OSS/Catch/projects/SelfTest/MiscTests.cpp
...............................................................................

Users/philnash/Dev/OSS/Catch/projects/SelfTest/MiscTests.cpp: FAILED:
explicitly with message:
  to infinity and beyond

Message from section one
Message from section two
Some information
An error
Message from section one
Message from section two
Some information
An error
hello
hello
-------------------------------------------------------------------------------
./failing/Tricky/non streamable type
-------------------------------------------------------------------------------
Users/philnash/Dev/OSS/Catch/projects/SelfTest/TrickyTests.cpp
...............................................................................

Users/philnash/Dev/OSS/Catch/projects/SelfTest/TrickyTests.cpp: FAILED:
  CHECK( &o1 == &o2 )
with expansion:
  0x<hex digits> == 0x<hex digits>

Users/philnash/Dev/OSS/Catch/projects/SelfTest/TrickyTests.cpp: FAILED:
  CHECK( o1 == o2 )
with expansion:
  {?} == {?}

-------------------------------------------------------------------------------
./failing/string literals
-------------------------------------------------------------------------------
Users/philnash/Dev/OSS/Catch/projects/SelfTest/TrickyTests.cpp
...............................................................................

Users/philnash/Dev/OSS/Catch/projects/SelfTest/TrickyTests.cpp: FAILED:
  REQUIRE( std::string( "first" ) == "second" )
with expansion:
  "first" == "second"

===============================================================================
121 test cases - 35 failed (744 assertions - 90 failed)

